[tox]
skipsdist = True
envlist = lint, test
all_sources = src/ tests/
requires =
    tox >= 4.0.0
    tox-uv

[testenv]
runner = uv-venv-lock-runner
setenv =
    PYTHONPATH = {toxinidir}/src

allowlist_externals =
    uv
    pre-commit

commands_pre = uv sync

[testenv:test]
description = Run tests
commands = uv run coverage run -m pytest
           uv run coverage combine
           uv run coverage report

[testenv:debug]
description = Run pytest with args (default '--lf --pdb')
commands =
    uv run pytest {posargs:--lf --pdb}


[testenv:lint]
description = Run mypy and ruff
deps = pre-commit
commands = pre-commit run --all-files
           uv run ruff format --diff {[tox]all_sources}
	         uv run ruff check --no-fix {[tox]all_sources}
	         uv run mypy --cache-dir /dev/null {[tox]all_sources}
